# Workflow based on that from godot-sqlite, by 2shady4u
name: 🐧 Linux
on:
  push:
    paths: [godot_qoi/**, .github/**, lib_utils.py, SConstruct]
  pull_request:
    types: [opened, edited]
  repository_dispatch:

# Global Settings
env:
  PROJECT_FOLDER: .
  TARGET_PATH: bin
  TARGET_NAME: libgodot_qoi

jobs:
  linux-compilation:
    name: Linux Compilation ${{ matrix.name }}
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            bits: 64
            bin: "bin/libgodot_qoi.linux.release.64.so"

          - name: x86
            bits: 32
            bin: "bin/libgodot_qoi.linux.release.32.so"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Linux dependencies
        shell: bash
        run: |
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install gcc-multilib g++-multilib
          #sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
          #    libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
          #    libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
          #    llvm libspeechd-dev speech-dispatcher

      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.x"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        run: |
          cd godot-cpp
          git apply ../godot_cpp_restrict_used_classes.patch
          scons platform=linux bits=${{ matrix.bits }} target=release generate_bindings=yes -j4
          cd ..
          scons platform=linux bits=${{ matrix.bits }} target=release -j4

      - name: Prepare artifact
        run: |
          strip ${{ matrix.bin }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          retention-days: 7
          path: ${{env.TARGET_PATH}}/*
