name: 🍏 MacOS
on:
  push:
    paths:
      [
        godot_qoi/**,
        .github/**,
        "!.github/**/util_*",
        "**.patch",
        lib_utils.py,
        SConstruct,
      ]
  repository_dispatch:

# Stop the same workflow actions
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  macos-gdextension:
    name: MacOS GDExtension ${{ matrix.arch }} ${{ matrix.target }}
    runs-on: "macos-latest"

    strategy:
      fail-fast: false
      matrix:
        arch: [universal]
        target: [editor, template_release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDExtension
        uses: ./.github/actions/compile_gdextension
        with:
          platform: macos
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          artifact: macos
