name: ↗️ Update binaries from artifacts

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      
      - name: Download Windows Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: windows_builds.yml
          path: extracted_files
      
      - name: Download Linux Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: linux_builds.yml
          path: extracted_files
      
      - name: Download MacOS Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: macos_builds.yml
          path: extracted_files
      
      - name: Replace with new files
        run: |
          ls extracted_files/*
          rm -rf addons/qoi/libs/
          mv -f extracted_files addons/qoi/libs

      - name: Commit report
        run: |
          git config --global user.name 'Auto Updater'
          git config --global user.email 'auto-updater@users.noreply.github.com'
          git add -A
          git commit -am "[CI] ↗️ Updated Binaries"
          git push