name: 🪟 Windows
on:
  push:
    paths: [godot_qoi/**, .github/**, '!.github/**/util_*', '**.patch', lib_utils.py, SConstruct]
  repository_dispatch:

# Stop the same workflow actions
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-gdextension:
    name: Windows GDExtension ${{ matrix.name }} ${{ matrix.target }}
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            arch: x86_64
            target: [editor, template_release]

          #- name: x86
          #  arch: x86_64
          #  target: [editor, template_release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDExtension 
        uses: ./.github/actions/compile_gdextension
        with:
          platform: windows
          target: ${{ matrix.target }}
          bits: arch=${{ matrix.arch }}
          artifact: win