name: 🪟 Windows
on:
  push:
    paths: [godot_qoi/**, .github/**, '!.github/**/util_*', '**.patch', lib_utils.py, SConstruct]
  repository_dispatch:

# Stop the same workflow actions
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-gdnative:
    name: Windows GDNative ${{ matrix.name }}
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            bits: 64

          - name: x86
            bits: 32

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDNative 
        uses: ./.github/actions/compile_gdnative
        with:
          platform: windows
          target: release
          bits: bits=${{ matrix.bits }}
          artifact: win